"""faz6 job matching

Revision ID: 22c306aaa51d
Revises: 2f777f604675
Create Date: 2026-07-03 22:07:02.014932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '22c306aaa51d'
down_revision: Union[str, Sequence[str], None] = '2f777f604675'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ai_output_type enum'ına Faz 6 için yeni değerler eklenir. Alembic autogenerate enum
    # değeri eklemelerini algılamadığı için elle yazılmıştır. Postgres'te ADD VALUE aynı
    # transaction içinde eklenip kullanılamaz; bu migration sadece ekler, kullanım sonraki
    # (ayrı) transaction'larda (uygulama istekleri) gerçekleşir.
    # NOT: SQLAlchemy'nin Enum(PythonEnum) tipi native Postgres enum'ında üye .value'sunu
    # değil .name'ini saklar (ör. "summary_rewrite" değil "SUMMARY_REWRITE") — mevcut
    # değerlerle tutarlı olması için burada da büyük harfli isim kullanılır.
    op.execute("ALTER TYPE ai_output_type ADD VALUE IF NOT EXISTS 'ATS_KEYWORD_INSERTION'")
    op.execute("ALTER TYPE ai_output_type ADD VALUE IF NOT EXISTS 'INTERVIEW_PREP'")
    op.execute("ALTER TYPE ai_output_type ADD VALUE IF NOT EXISTS 'SALARY_ESTIMATION'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_descriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('company', sa.String(length=200), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_descriptions_user_id'), 'job_descriptions', ['user_id'], unique=False)
    op.create_table('job_matches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('job_description_id', sa.UUID(), nullable=False),
    sa.Column('cv_document_id', sa.UUID(), nullable=False),
    sa.Column(
        'status',
        postgresql.ENUM('PENDING', 'COMPLETED', 'FAILED', name='analysis_status', create_type=False),
        nullable=False,
    ),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cv_document_id'], ['cv_documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_description_id'], ['job_descriptions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_matches_cv_document_id'), 'job_matches', ['cv_document_id'], unique=False)
    op.create_index(op.f('ix_job_matches_job_description_id'), 'job_matches', ['job_description_id'], unique=False)
    op.create_index(op.f('ix_job_matches_user_id'), 'job_matches', ['user_id'], unique=False)
    op.add_column('ai_outputs', sa.Column('job_description_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_ai_outputs_job_description_id'), 'ai_outputs', ['job_description_id'], unique=False)
    op.create_foreign_key(None, 'ai_outputs', 'job_descriptions', ['job_description_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ai_outputs', type_='foreignkey')
    op.drop_index(op.f('ix_ai_outputs_job_description_id'), table_name='ai_outputs')
    op.drop_column('ai_outputs', 'job_description_id')
    op.drop_index(op.f('ix_job_matches_user_id'), table_name='job_matches')
    op.drop_index(op.f('ix_job_matches_job_description_id'), table_name='job_matches')
    op.drop_index(op.f('ix_job_matches_cv_document_id'), table_name='job_matches')
    op.drop_table('job_matches')
    op.drop_index(op.f('ix_job_descriptions_user_id'), table_name='job_descriptions')
    op.drop_table('job_descriptions')
    # ### end Alembic commands ###
