"""faz5 ai outputs

Revision ID: 2f777f604675
Revises: c760b14c0ac0
Create Date: 2026-07-03 21:18:57.357033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2f777f604675'
down_revision: Union[str, Sequence[str], None] = 'c760b14c0ac0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_outputs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cv_document_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('output_type', sa.Enum('SUMMARY_REWRITE', 'EXPERIENCE_REWRITE', 'SKILLS_REWRITE', 'ATS_OPTIMIZATION', 'COVER_LETTER', 'LINKEDIN_SUMMARY', name='ai_output_type'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('input_context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cv_document_id'], ['cv_documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_outputs_cv_document_id'), 'ai_outputs', ['cv_document_id'], unique=False)
    op.create_index(op.f('ix_ai_outputs_output_type'), 'ai_outputs', ['output_type'], unique=False)
    op.create_index(op.f('ix_ai_outputs_user_id'), 'ai_outputs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_outputs_user_id'), table_name='ai_outputs')
    op.drop_index(op.f('ix_ai_outputs_output_type'), table_name='ai_outputs')
    op.drop_index(op.f('ix_ai_outputs_cv_document_id'), table_name='ai_outputs')
    op.drop_table('ai_outputs')
    # ### end Alembic commands ###
