"""faz3 cv analysis version

Revision ID: c760b14c0ac0
Revises: 09f1ba519b2f
Create Date: 2026-07-03 15:50:20.344750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c760b14c0ac0'
down_revision: Union[str, Sequence[str], None] = '09f1ba519b2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cv_analyses', sa.Column('version', sa.Integer(), nullable=False))
    op.create_unique_constraint('uq_cv_analyses_document_version', 'cv_analyses', ['cv_document_id', 'version'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_cv_analyses_document_version', 'cv_analyses', type_='unique')
    op.drop_column('cv_analyses', 'version')
    # ### end Alembic commands ###
